// actionTypes.js
export const GET_ANALYTICS = "GET_ANALYTICS";
export const GET_ANALYTICS_SUCCESS = "GET_ANALYTICS_SUCCESS";
export const GET_ANALYTICS_FAIL = "GET_ANALYTICS_FAIL";
export const SET_ANALYTICS_LOADING = "SET_ANALYTICS_LOADING";
